name: Kotlin CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'gradle'
      - name: Grant execute permission for gradlew in sms-consumer
        run: chmod +x sms-consumer/gradlew
      - name: Run tests for sms-consumer
        run: ./sms-consumer/gradlew test
      - name: Grant execute permission for gradlew in sms-producer
        run: chmod +x sms-producer/gradlew
      - name: Run tests for sms-producer
        run: ./sms-producer/gradlew test
